minha pasta
mata56-ic-ufba/caracterizacao pull request #33
Opened 2021-08-30 17:58 UTC by tvieira99

2021-08-30 18:19 UTC, christinaflachufba requested changes
Oi Thiago,

Por favor, poderia renomear os arquivos L1 e L2, para colocar seu usuario github, por exemplo, L1-tvieira99.md?

2021-08-30 18:29 UTC, christinaflachufba commented
Por favor, renomear antes da próxima aula, certo?

2021-08-31 01:46 UTC, tvieira99 commented
Efetuei as mudanças

2021-09-01 15:51 UTC, christinaflachufba commented
Olá, conseguiu alterar?

2021-09-01 15:52 UTC, merged

2021-09-01 15:57 UTC, tvieira99 commented
Sim

Em qua, 1 de set de 2021 12:52, Prof Christina Flach <
***@***.***> escreveu:

> Merged #33 <https://github.com/mata56-ic-ufba/caracterizacao/pull/33>
> into main.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mata56-ic-ufba/caracterizacao/pull/33#event-5240583350>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3N7CBB4B5UXTATFOGANCLT7ZD4ZANCNFSM5DCMCJEA>
> .
>